[project]
name = "code"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "darts>=0.35.0",
    "ipykernel>=6.29.5",
    "nbformat>=5.10.4",
    "plotly>=6.1.2",
    "polars>=1.30.0",
    "scikit-learn>=1.6.1",
]
